# CORS 許可
[[headers]]
  for = "/thanksad/safe/json/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# 存在しないファイルをリダイレクト用
[[edge_functions]]
  path = "/thanksad/safe/json/*"
  function = "thanksad-json"