[build]
  command = "npm run build"
  publish = "public"

# CORS 許可
[[headers]]
  for = "/thanksad/json/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# 存在しないファイルをリダイレクト用
[[edge_functions]]
  path = "/thanksad/safe/json/*"
  function = "thanksad-json"

# rootにリクエストした場合、webridgeにリダイレクト
[[redirects]]
  from = "/"
  to = "https://webridge.net/"
  status = 301
  force = true
